# Generated by Django 5.0.6 on 2024-05-16 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0002_reviwer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reviwer',
            new_name='Review',
        ),
    ]
