# Generated by Django 5.0.6 on 2024-05-18 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskManager', '0003_rename_reviwer_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
